### ISSUE TITLE
Shopping List / Bill of Materials

### ISSUE THREAD

**Issue by JeffreyRodriguez** [JeffreyRodriguez/Liberator12k#3]
I need to get a nice BOM together, but this is a start... it is incomplete.

#### Frame
2pcs 10x1/2"-13 Hex Bolts (Grade 2 is fine)
2pcs 1/2"-13 Hex Nuts
2pcs 1 1/2x1/4"-20 Flat head bolt
2pcs 1/4"-20 Heatset Nuts (or hex nuts)

#### Barrel
3/4" Sch40 gas pipe, at least 2' for a break-action. Comes in a range of lengths in the plumbing section of your local hardware store.

In a pinch, 1/2" threaded rod and nuts to match.

#### Lower
1/4" square rod (Buy a 3' stick... or longer)
5/16" square rod

**Comment by konekilla** [comment]
**Reciever**
1pcs 1 1/2" DWV ABS drain tube 12-15" length
1pcs 1" PVC Pipe 6" length
