### ISSUE TITLE
Frame.scad unable to render

### ISSUE THREAD

**Issue by flintsaw** [JeffreyRodriguez/Liberator12k#8]
Throws error:
CGAL error in CGAL_Nef_polyhedron3(): CGAL ERROR: assertion violation!
Expr: e_below != SHalfedge_handle()
File: /usr/include/CGAL/Nef_3/SNC_FM_decorator.h
Line: 427

Attempted to fix as a thank you but no dice.

**Comment by JeffreyRodriguez** [comment]
Hi flintsaw, thanks for the bug report. Which commit/branch are you on?

**Comment by flintsaw** [comment]
This was the master branch. Had errors on the more current branch as well but didn’t chase those down.

**Comment by flintsaw** [comment]
Update! I was getting the error on OpenSCAD 2021.01 but the AppImage works great as of 5/28/21.

**Comment by JeffreyRodriguez** [comment]
Good to hear... I should document the minimum version.
